services:
  # PostgreSQL Database
  - type: pserv
    name: melbourne-parking-db
    env: python
    plan: free
    databaseName: melbourne_parking
    user: melbourne_user

  # Backend API Service
  - type: web
    name: melbourne-parking-api
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT main:app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: melbourne-parking-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

  # Frontend Static Site
  - type: web
    name: melbourne-parking-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: melbourne-parking-api
          property: host
